/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRuntimeRouteImport } from './routes/settings/runtime'
import { Route as SettingsCloudflareRouteImport } from './routes/settings/cloudflare'
import { Route as PillsPillIdRouteImport } from './routes/pills/$pillId'
import { Route as ApiRunsRunIdTerminalRouteImport } from './routes/api/runs/$runId/terminal'
import { Route as ApiRunsRunIdMetricsRouteImport } from './routes/api/runs/$runId/metrics'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRuntimeRoute = SettingsRuntimeRouteImport.update({
  id: '/settings/runtime',
  path: '/settings/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCloudflareRoute = SettingsCloudflareRouteImport.update({
  id: '/settings/cloudflare',
  path: '/settings/cloudflare',
  getParentRoute: () => rootRouteImport,
} as any)
const PillsPillIdRoute = PillsPillIdRouteImport.update({
  id: '/pills/$pillId',
  path: '/pills/$pillId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdTerminalRoute = ApiRunsRunIdTerminalRouteImport.update({
  id: '/api/runs/$runId/terminal',
  path: '/api/runs/$runId/terminal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunsRunIdMetricsRoute = ApiRunsRunIdMetricsRouteImport.update({
  id: '/api/runs/$runId/metrics',
  path: '/api/runs/$runId/metrics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/pills/$pillId': typeof PillsPillIdRoute
  '/settings/cloudflare': typeof SettingsCloudflareRoute
  '/settings/runtime': typeof SettingsRuntimeRoute
  '/api/runs/$runId/metrics': typeof ApiRunsRunIdMetricsRoute
  '/api/runs/$runId/terminal': typeof ApiRunsRunIdTerminalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/pills/$pillId': typeof PillsPillIdRoute
  '/settings/cloudflare': typeof SettingsCloudflareRoute
  '/settings/runtime': typeof SettingsRuntimeRoute
  '/api/runs/$runId/metrics': typeof ApiRunsRunIdMetricsRoute
  '/api/runs/$runId/terminal': typeof ApiRunsRunIdTerminalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/pills/$pillId': typeof PillsPillIdRoute
  '/settings/cloudflare': typeof SettingsCloudflareRoute
  '/settings/runtime': typeof SettingsRuntimeRoute
  '/api/runs/$runId/metrics': typeof ApiRunsRunIdMetricsRoute
  '/api/runs/$runId/terminal': typeof ApiRunsRunIdTerminalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/pills/$pillId'
    | '/settings/cloudflare'
    | '/settings/runtime'
    | '/api/runs/$runId/metrics'
    | '/api/runs/$runId/terminal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/pills/$pillId'
    | '/settings/cloudflare'
    | '/settings/runtime'
    | '/api/runs/$runId/metrics'
    | '/api/runs/$runId/terminal'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/pills/$pillId'
    | '/settings/cloudflare'
    | '/settings/runtime'
    | '/api/runs/$runId/metrics'
    | '/api/runs/$runId/terminal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  PillsPillIdRoute: typeof PillsPillIdRoute
  SettingsCloudflareRoute: typeof SettingsCloudflareRoute
  SettingsRuntimeRoute: typeof SettingsRuntimeRoute
  ApiRunsRunIdMetricsRoute: typeof ApiRunsRunIdMetricsRoute
  ApiRunsRunIdTerminalRoute: typeof ApiRunsRunIdTerminalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/runtime': {
      id: '/settings/runtime'
      path: '/settings/runtime'
      fullPath: '/settings/runtime'
      preLoaderRoute: typeof SettingsRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/cloudflare': {
      id: '/settings/cloudflare'
      path: '/settings/cloudflare'
      fullPath: '/settings/cloudflare'
      preLoaderRoute: typeof SettingsCloudflareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pills/$pillId': {
      id: '/pills/$pillId'
      path: '/pills/$pillId'
      fullPath: '/pills/$pillId'
      preLoaderRoute: typeof PillsPillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/terminal': {
      id: '/api/runs/$runId/terminal'
      path: '/api/runs/$runId/terminal'
      fullPath: '/api/runs/$runId/terminal'
      preLoaderRoute: typeof ApiRunsRunIdTerminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$runId/metrics': {
      id: '/api/runs/$runId/metrics'
      path: '/api/runs/$runId/metrics'
      fullPath: '/api/runs/$runId/metrics'
      preLoaderRoute: typeof ApiRunsRunIdMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  PillsPillIdRoute: PillsPillIdRoute,
  SettingsCloudflareRoute: SettingsCloudflareRoute,
  SettingsRuntimeRoute: SettingsRuntimeRoute,
  ApiRunsRunIdMetricsRoute: ApiRunsRunIdMetricsRoute,
  ApiRunsRunIdTerminalRoute: ApiRunsRunIdTerminalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
